version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  cliente-persona-service:
    build:
      context: ./cliente-persona-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker

  cuenta-movimiento-service:
    build:
      context: ./cuenta-movimiento-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - cliente-persona-service
      - cuenta-movimiento-service
